# Generated by Django 5.1.2 on 2024-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('no_kartu', models.IntegerField(verbose_name=10)),
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id_matkul', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
