# Generated by Django 5.1.2 on 2024-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0002_alter_matkul_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id_dosen', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dosen',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswaa',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nokartu', models.IntegerField(verbose_name=10)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mahasiswaa',
            },
        ),
    ]
