# Generated by Django 5.1.2 on 2024-10-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0003_dosen_mahasiswaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrak',
            fields=[
                ('id_kontrak', models.IntegerField(primary_key=True, serialize=False)),
                ('id_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontak', to='connectdb.dosen')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontrak', to='connectdb.matkul')),
                ('id_mhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontrak', to='connectdb.mahasiswaa')),
            ],
            options={
                'db_table': 'kontrak',
            },
        ),
    ]
