# Generated by Django 5.1.2 on 2024-10-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0004_kontrak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mahasiswa',
        ),
    ]
