# Generated by Django 5.1.2 on 2024-10-30 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0005_delete_mahasiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='matkul',
            name='dosen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matkul', to='connectdb.dosen'),
        ),
    ]
