# Generated by Django 5.1.2 on 2024-10-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0006_matkul_dosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dosenbaru',
            },
        ),
        migrations.CreateModel(
            name='Matkul2',
            fields=[
                ('id_matkul2', models.IntegerField(primary_key=True, serialize=False)),
                ('nama2', models.CharField(max_length=100)),
                ('dosen2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matkul', to='connectdb.dosen2')),
            ],
            options={
                'db_table': 'matkulbaru',
            },
        ),
    ]
