# Generated by Django 5.1.2 on 2024-10-31 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0007_dosen2_matkul2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkul2',
            name='dosen2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matkulbaru', to='connectdb.dosen2'),
        ),
    ]
