# Generated by Django 5.1.2 on 2024-11-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0008_alter_matkul2_dosen2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matkul2',
            name='dosen2',
        ),
        migrations.DeleteModel(
            name='Dosen2',
        ),
        migrations.DeleteModel(
            name='Matkul2',
        ),
    ]
