# Generated by Django 5.1.2 on 2024-11-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0009_remove_matkul2_dosen2_delete_dosen2_delete_matkul2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkul',
            name='dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matkul', to='connectdb.dosen'),
        ),
    ]
