# Generated by Django 5.1.2 on 2024-11-07 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0010_alter_matkul_dosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id_kelas', models.IntegerField(primary_key=True, serialize=False)),
                ('nm_kelas', models.CharField(max_length=100)),
                ('id_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen', to='connectdb.dosen')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='connectdb.matkul')),
            ],
        ),
    ]
