# Generated by Django 5.1.2 on 2024-11-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0011_kelas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kelas',
            table='kelas',
        ),
    ]
