# Generated by Django 5.1.2 on 2024-11-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0013_kontrak_id_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matkul',
            name='dosen',
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='connectdb.dosen'),
        ),
        migrations.AlterModelTable(
            name='matkul',
            table=None,
        ),
    ]
