# Generated by Django 5.1.2 on 2024-11-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0014_remove_matkul_dosen_alter_kelas_id_dosen_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matkul',
            table='matkul',
        ),
    ]
