# Generated by Django 5.1.2 on 2024-11-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0015_alter_matkul_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrak',
            name='id_dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectdb.dosen'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='id_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectdb.kelas'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='id_matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectdb.matkul'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='id_mhs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectdb.mahasiswaa'),
        ),
    ]
