# Generated by Django 5.1.2 on 2024-11-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0017_remove_kontrak_id_dosen_remove_kontrak_id_matkul'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='kontrak',
        #     name='id_kelas',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectdb.kelas'),
        # ),
        # migrations.AlterField(
        #     model_name='kontrak',
        #     name='id_mhs',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectdb.mahasiswaa'),
        # ),
    ]
