# Generated by Django 5.1.2 on 2024-11-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0018_alter_kontrak_id_kelas_alter_kontrak_id_mhs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrak',
            name='id_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectdb.kelas'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='id_mhs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectdb.mahasiswaa'),
        ),
    ]
