# Generated by Django 5.1.2 on 2024-11-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen2',
            fields=[
                ('id_dosen', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dosen2',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswaa2',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nokartu', models.IntegerField(verbose_name=10)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mahasiswaa2',
            },
        ),
        migrations.CreateModel(
            name='Matkul2',
            fields=[
                ('id_matkul', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'matkul2',
            },
        ),
    ]
