# Generated by Django 5.1.2 on 2024-11-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas2',
            fields=[
                ('id_kelas', models.IntegerField(primary_key=True, serialize=False)),
                ('nm_kelas', models.CharField(max_length=100)),
                ('id_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.dosen2')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.matkul2')),
            ],
            options={
                'db_table': 'kelas2',
            },
        ),
        migrations.CreateModel(
            name='Kontrak2',
            fields=[
                ('id_kontrak', models.IntegerField(primary_key=True, serialize=False)),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.kelas2')),
                ('id_mhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.mahasiswaa2')),
            ],
            options={
                'db_table': 'kontrak2',
            },
        ),
    ]
