# Generated by Django 5.1.2 on 2024-11-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_kelas2_kontrak2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id_kehdiran', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.IntegerField()),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.kelas2')),
                ('id_mhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.mahasiswaa2')),
            ],
            options={
                'db_table': 'kehadiran',
            },
        ),
    ]
