# Generated by Django 5.1.2 on 2024-11-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_kehadiran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
